import { CandidateProfile, Institute, Job, Application, DPDPDataRequest, AuditLog } from '@/types';

export const INITIAL_INSTITUTES: Institute[] = [
  {
    id: 'inst-iitb',
    name: 'Indian Institute of Technology Bombay',
    shortName: 'IIT Bombay',
    type: 'IIT / NIT / IISc / IIIT (Institute of National Importance)',
    location: {
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400076',
      campusType: 'Residential Mega Campus',
    },
    accreditation: {
      naacGrade: 'A++',
      naacScore: 3.89,
      nirfRankOverall: 3,
      nirfRankUniversity: 3,
      nirfRankEngineering: 1,
      aicteApproved: true,
      ugc2f12bStatus: true,
      nbaAccreditedDepts: ['Computer Science and Engineering', 'Electrical Engineering', 'Mechanical Engineering', 'Chemical Engineering'],
    },
    departments: [
      'Department of Computer Science and Engineering',
      'Department of Electrical Engineering',
      'Centre for Machine Intelligence and Data Science (C-MInDS)',
      'Department of Energy Science and Engineering',
      'Department of Biosciences and Bioengineering',
    ],
    aisheCode: 'U-0306',
    establishedYear: 1958,
    website: 'https://www.iitb.ac.in',
    logo: 'https://images.unsplash.com/photo-1562774053-701939374585?w=160&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1200&auto=format&fit=crop&q=80',
    verificationStatus: 'verified',
    verifiedAt: '2026-01-15',
    about: 'IIT Bombay is recognized worldwide as a leader in the field of engineering education and research. As an Institute of Eminence, it attracts the finest faculty from across the globe.',
    contactEmail: 'facrec@iitb.ac.in',
    contactPhone: '+91-22-2576-7000',
    stats: {
      facultyCount: 680,
      studentCount: 12500,
      patentsFiled: 420,
      hIndexAverage: 48,
    },
  },
  {
    id: 'inst-iisc',
    name: 'Indian Institute of Science Bangalore',
    shortName: 'IISc Bangalore',
    type: 'IIT / NIT / IISc / IIIT (Institute of National Importance)',
    location: {
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560012',
      campusType: 'Residential Mega Campus',
    },
    accreditation: {
      naacGrade: 'A++',
      naacScore: 3.94,
      nirfRankOverall: 2,
      nirfRankUniversity: 1,
      nirfRankEngineering: 2,
      aicteApproved: true,
      ugc2f12bStatus: true,
      nbaAccreditedDepts: ['Computational and Data Sciences', 'Centre for Nano Science', 'Electrical Communication Engineering'],
    },
    departments: [
      'Department of Computational and Data Sciences (CDS)',
      'Department of Computer Science and Automation (CSA)',
      'Centre for Nano Science and Engineering (CeNSE)',
      'Department of Electronic Systems Engineering (DESE)',
      'Department of Biochemistry',
    ],
    aisheCode: 'U-0220',
    establishedYear: 1909,
    website: 'https://www.iisc.ac.in',
    logo: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=160&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200&auto=format&fit=crop&q=80',
    verificationStatus: 'verified',
    verifiedAt: '2026-01-10',
    about: 'IISc is India’s premier university for scientific research and higher education, leading nation-building fundamental and applied scientific discoveries for over a century.',
    contactEmail: 'dean.faculty@iisc.ac.in',
    contactPhone: '+91-80-2293-2001',
    stats: {
      facultyCount: 520,
      studentCount: 4600,
      patentsFiled: 850,
      hIndexAverage: 62,
    },
  },
  {
    id: 'inst-bits',
    name: 'Birla Institute of Technology and Science, Pilani',
    shortName: 'BITS Pilani',
    type: 'Premier Private University',
    location: {
      city: 'Pilani',
      state: 'Rajasthan',
      pincode: '333031',
      campusType: 'Residential Mega Campus',
    },
    accreditation: {
      naacGrade: 'A++',
      naacScore: 3.78,
      nirfRankOverall: 20,
      nirfRankUniversity: 11,
      nirfRankEngineering: 18,
      aicteApproved: true,
      ugc2f12bStatus: true,
      nbaAccreditedDepts: ['Computer Science and Information Systems', 'Electrical and Electronics', 'Chemical Engineering'],
    },
    departments: [
      'Department of Computer Science & Information Systems',
      'Department of Electrical & Electronics Engineering',
      'Department of Biological Sciences',
      'Department of Humanities and Social Sciences',
      'Department of Management',
    ],
    aisheCode: 'U-0391',
    establishedYear: 1964,
    website: 'https://www.bits-pilani.ac.in',
    logo: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=160&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=1200&auto=format&fit=crop&q=80',
    verificationStatus: 'verified',
    verifiedAt: '2026-01-20',
    about: 'An Institution of Eminence recognized for excellence in technical and interdisciplinary higher education with campuses in Pilani, Goa, Hyderabad, and Dubai.',
    contactEmail: 'facultyrecruitment@pilani.bits-pilani.ac.in',
    contactPhone: '+91-1596-242210',
    stats: {
      facultyCount: 950,
      studentCount: 17000,
      patentsFiled: 260,
      hIndexAverage: 36,
    },
  },
  {
    id: 'inst-du',
    name: 'University of Delhi',
    shortName: 'Delhi University',
    type: 'Central University (Govt. of India)',
    location: {
      city: 'New Delhi',
      state: 'Delhi',
      pincode: '110007',
      campusType: 'Urban',
    },
    accreditation: {
      naacGrade: 'A++',
      naacScore: 3.65,
      nirfRankOverall: 11,
      nirfRankUniversity: 6,
      aicteApproved: true,
      ugc2f12bStatus: true,
      nbaAccreditedDepts: ['Department of Computer Science', 'Faculty of Technology'],
    },
    departments: [
      'Department of Computer Science',
      'Cluster Innovation Centre (CIC)',
      'Department of Physics & Astrophysics',
      'Faculty of Technology',
      'Department of Economics',
    ],
    aisheCode: 'U-0100',
    establishedYear: 1922,
    website: 'https://www.du.ac.in',
    logo: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=160&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=1200&auto=format&fit=crop&q=80',
    verificationStatus: 'verified',
    verifiedAt: '2026-02-01',
    about: 'The University of Delhi is a premier collegiate public central university in New Delhi, known for high standards in teaching and research across diverse disciplines.',
    contactEmail: 'recruitment@admin.du.ac.in',
    contactPhone: '+91-11-2700-1000',
    stats: {
      facultyCount: 1400,
      studentCount: 65000,
      patentsFiled: 180,
      hIndexAverage: 42,
    },
  },
  {
    id: 'inst-anna',
    name: 'Anna University',
    shortName: 'Anna University',
    type: 'State Public University',
    location: {
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600025',
      campusType: 'Urban',
    },
    accreditation: {
      naacGrade: 'A++',
      naacScore: 3.71,
      nirfRankOverall: 14,
      nirfRankUniversity: 13,
      nirfRankEngineering: 13,
      aicteApproved: true,
      ugc2f12bStatus: true,
      nbaAccreditedDepts: ['Department of Information Technology', 'Department of ECE', 'Department of Civil Engineering'],
    },
    departments: [
      'Department of Information Science and Technology',
      'Department of Electronics and Communication Engineering',
      'Department of Computer Science and Engineering',
      'Centre for Cyber Security',
    ],
    aisheCode: 'U-0439',
    establishedYear: 1978,
    website: 'https://www.annauniv.edu',
    logo: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=160&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=1200&auto=format&fit=crop&q=80',
    verificationStatus: 'verified',
    verifiedAt: '2026-01-28',
    about: 'Anna University is a public state university offering higher education in Engineering, Technology, Architecture and Applied Sciences relevant to current societal needs.',
    contactEmail: 'registrar@annauniv.edu',
    contactPhone: '+91-44-2235-7004',
    stats: {
      facultyCount: 820,
      studentCount: 16000,
      patentsFiled: 310,
      hIndexAverage: 39,
    },
  },
  {
    id: 'inst-ashoka',
    name: 'Ashoka University',
    shortName: 'Ashoka University',
    type: 'Premier Private University',
    location: {
      city: 'Sonipat',
      state: 'Haryana',
      pincode: '131029',
      campusType: 'Residential Mega Campus',
    },
    accreditation: {
      naacGrade: 'A+',
      naacScore: 3.42,
      nirfRankOverall: 88,
      nirfRankUniversity: 52,
      aicteApproved: false,
      ugc2f12bStatus: true,
      nbaAccreditedDepts: [],
    },
    departments: [
      'Department of Computer Science',
      'Department of Economics',
      'Trivedi School of Biosciences',
      'Department of Sociology and Anthropology',
    ],
    aisheCode: 'U-0761',
    establishedYear: 2014,
    website: 'https://www.ashoka.edu.in',
    logo: 'https://images.unsplash.com/photo-1576495199011-ab917353bb8f?w=160&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=1200&auto=format&fit=crop&q=80',
    verificationStatus: 'verified',
    verifiedAt: '2026-02-10',
    about: 'A pioneering liberal arts and sciences university dedicated to providing an exceptional multidisciplinary education with strong global faculty and research culture.',
    contactEmail: 'faculty.hiring@ashoka.edu.in',
    contactPhone: '+91-130-230-0000',
    stats: {
      facultyCount: 210,
      studentCount: 2800,
      patentsFiled: 45,
      hIndexAverage: 32,
    },
  },
];

export const INITIAL_JOBS: Job[] = [
  {
    id: 'job-iitb-cse-101',
    instituteId: 'inst-iitb',
    instituteName: 'Indian Institute of Technology Bombay',
    instituteShortName: 'IIT Bombay',
    instituteLogo: 'https://images.unsplash.com/photo-1562774053-701939374585?w=160&auto=format&fit=crop&q=80',
    instituteType: 'IIT / NIT / IISc / IIIT (Institute of National Importance)',
    title: 'Assistant Professor (Grade I - Level 12) in Artificial Intelligence & Generative Systems',
    designation: 'Assistant Professor (Level 12 - 7th CPC)',
    department: 'Department of Computer Science and Engineering',
    specializationTags: ['Large Language Models', 'Reinforcement Learning', 'Generative AI', 'Deep Learning Systems', 'Computer Vision'],
    advertisementNumber: 'IITB/FA/2026/CSE/01',
    location: {
      city: 'Mumbai',
      state: 'Maharashtra',
    },
    payScale: {
      cpcBand: 'Level 12 (₹1,01,500 - ₹1,67,400)',
      entryPay: '₹1,01,500',
      grossMonthlyEstimated: '₹1,88,000/mo (Entry pay + 50% DA + 27% HRA + TA)',
      allowances: ['Institute Seed Research Grant up to ₹25 Lakhs', 'Full Campus Housing', 'CPDA ₹3 Lakhs/block', 'Children Education Allowance'],
    },
    requiredQualifications: {
      minDegree: 'Ph.D. Mandatory',
      netSletMandatory: false,
      phdNorms: 'UGC 2009/2016 Compliant',
      minExperienceYears: 3,
      minUgcCarePubs: 4,
      ugcRegulationsYear: 'UGC 2018 Regulations',
      specializationRequirements: [
        'Ph.D. in Computer Science, Machine Learning, or related field with top-tier publications (NeurIPS, ICML, ICLR, CVPR, ACL)',
        'Minimum 3 years of post-Ph.D. research or industrial R&D experience',
        'Proven track record of high-impact research papers in Scopus/SCI indexed venues',
      ],
    },
    reservationCategory: 'Open to All Categories',
    applicationDeadline: '2026-09-30',
    status: 'published',
    isClaimedByInstitute: true,
    screeningQuestions: [
      'Do you have at least 2 first-author papers in Tier-1 venues (NeurIPS, ICML, CVPR, ICLR, ACL, KDD)?',
      'State your total citation count and current Google Scholar h-index.',
      'Briefly describe your proposed research laboratory plan and external grant potential for the next 3 years.',
    ],
    selectionProcess: [
      'Initial Screening by Departmental Faculty Search Committee (DFSC)',
      'Shortlisting based on API scores & Publication Impact Factor',
      'Technical Research Seminar Presentation to Department Faculty',
      'Selection Committee Interview with Board of Governors Representatives',
      'Formal Offer & 7th CPC Appointment Letter',
    ],
    description: 'The Department of Computer Science and Engineering at IIT Bombay invites applications from highly accomplished scholars with outstanding research records for Assistant Professor Grade-I positions. The candidate will establish an active research laboratory, mentor Ph.D. and M.Tech scholars, and teach undergraduate and postgraduate core AI/CS courses.',
    responsibilities: [
      'Develop and lead funded research projects in frontier Machine Learning and Generative AI',
      'Teach foundational and advanced CS courses (CS725 Machine Learning, CS747 Reinforcement Learning)',
      'Supervise doctoral dissertations and master theses',
      'Participate in academic administration and institutional development',
    ],
    benefits: [
      'Subsidized 3BHK on-campus residential quarters inside the scenic Powai campus',
      'Cumulative Professional Development Allowance (CPDA) of ₹3,00,000 every 3-year block',
      'Access to Param Seva Supercomputing Cluster and dedicated H100 GPU computing nodes',
      'Contributory Provident Fund / National Pension System (NPS) with full medical coverage at IIT Hospital',
    ],
    postedAt: '2026-08-15',
    applicantCount: 28,
    featured: true,
  },
  {
    id: 'job-iisc-cds-102',
    instituteId: 'inst-iisc',
    instituteName: 'Indian Institute of Science Bangalore',
    instituteShortName: 'IISc Bangalore',
    instituteLogo: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=160&auto=format&fit=crop&q=80',
    instituteType: 'IIT / NIT / IISc / IIIT (Institute of National Importance)',
    title: 'Associate Professor (Level 13A) in Scalable Data Systems & Cloud Computing',
    designation: 'Associate Professor (Level 13A - 7th CPC)',
    department: 'Department of Computational and Data Sciences (CDS)',
    specializationTags: ['Distributed Systems', 'Cloud Computing', 'Database Kernels', 'Big Data Architecture', 'HPC'],
    advertisementNumber: 'IISc/R(HR)/2026/CDS-04',
    location: {
      city: 'Bengaluru',
      state: 'Karnataka',
    },
    payScale: {
      cpcBand: 'Level 13A2 (₹1,39,600 - ₹2,11,800)',
      entryPay: '₹1,39,600',
      grossMonthlyEstimated: '₹2,55,000/mo (Entry pay + 50% DA + 27% HRA + TA)',
      allowances: ['Startup Grant up to ₹40 Lakhs', 'Faculty Housing in Malleshwaram Campus', 'International Conference Travel Grant'],
    },
    requiredQualifications: {
      minDegree: 'Ph.D. Mandatory',
      netSletMandatory: false,
      phdNorms: 'UGC 2009/2016 Compliant',
      minExperienceYears: 6,
      minUgcCarePubs: 8,
      ugcRegulationsYear: 'UGC 2018 Regulations',
      specializationRequirements: [
        'Ph.D. in Computer Science / Systems with minimum 6 years of post-PhD teaching/research experience at Assistant Professor Level 12 or equivalent',
        'Demonstrated track record of graduating Ph.D. scholars',
        'Top-tier systems publications (OSDI, SOSP, VLDB, SIGMOD, FAST, EuroSys)',
      ],
    },
    reservationCategory: 'Unreserved (UR / General)',
    applicationDeadline: '2026-10-15',
    status: 'published',
    isClaimedByInstitute: true,
    screeningQuestions: [
      'How many Ph.D. scholars have you successfully graduated as primary advisor?',
      'Have you secured sponsored research grants exceeding ₹50 Lakhs from DST/SERB/MeitY or Industry?',
    ],
    selectionProcess: [
      'CDS Faculty Search Committee Evaluation',
      'Institute Standing Committee Review',
      'Open Colloquium and Interaction with Research Scholars',
      'Statutory Selection Committee chaired by the Director',
    ],
    description: 'IISc Bangalore invites visionary researchers to join the Department of Computational and Data Sciences as Associate Professor. The ideal candidate will spearhead breakthroughs in modern distributed systems, data-intensive computing, and high-performance database architectures.',
    responsibilities: [
      'Lead a world-class research group in Distributed Systems and Cloud Infrastructures',
      'Deliver cutting-edge postgraduate courses in Data Systems and Cloud Computing',
      'Establish strategic collaborations with national computing initiatives and global research labs',
    ],
    benefits: [
      'Campus housing in the central Bengaluru campus',
      'Highest institutional seed grant in India with dedicated research lab space',
      'Comprehensive healthcare at IISc Health Centre and empanelled super-specialty hospitals',
    ],
    postedAt: '2026-08-20',
    applicantCount: 14,
    featured: true,
  },
  {
    id: 'job-bits-cs-103',
    instituteId: 'inst-bits',
    instituteName: 'Birla Institute of Technology and Science, Pilani',
    instituteShortName: 'BITS Pilani',
    instituteLogo: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=160&auto=format&fit=crop&q=80',
    instituteType: 'Premier Private University',
    title: 'Assistant Professor (Level 10 / 11) in Cybersecurity & Cryptography',
    designation: 'Assistant Professor (Level 10 - 7th CPC)',
    department: 'Department of Computer Science & Information Systems',
    specializationTags: ['Cybersecurity', 'Applied Cryptography', 'Network Security', 'Post-Quantum Crypto', 'Zero-Trust'],
    advertisementNumber: 'BITS/REC/2026/CS-09',
    location: {
      city: 'Pilani',
      state: 'Rajasthan',
    },
    payScale: {
      cpcBand: 'Level 10 (₹57,700 - ₹1,82,400) + BITS Performance Allowance',
      entryPay: '₹70,900',
      grossMonthlyEstimated: '₹1,35,000/mo (Consolidated with BITS Top-Up)',
      allowances: ['OPER (Off-Campus Professional Allowance)', 'Seed Grant ₹10 Lakhs', 'On-Campus Bungalow / Apartment', 'Medical Insurance for Family'],
    },
    requiredQualifications: {
      minDegree: 'Ph.D. with First Class Master',
      netSletMandatory: false,
      phdNorms: 'UGC 2009/2016 Compliant',
      minExperienceYears: 0,
      minUgcCarePubs: 3,
      ugcRegulationsYear: 'UGC 2018 Regulations',
      specializationRequirements: [
        'First class in Master and Bachelor degrees, with a Ph.D. in Computer Science / Information Security',
        'Fresh Ph.D. graduates with strong publication records in IEEE S&P, ACM CCS, USENIX Security, NDSS, or Eurocrypt are encouraged to apply',
      ],
    },
    reservationCategory: 'Open to All Categories',
    applicationDeadline: '2026-09-25',
    status: 'published',
    isClaimedByInstitute: true,
    screeningQuestions: [
      'Do you have direct hands-on experience in vulnerability assessment or cryptographic protocol design?',
      'Which campus would be your primary preference (Pilani, Goa, or Hyderabad)?',
    ],
    selectionProcess: [
      'Cross-Campus Departmental Screening',
      'Online Research Talk to BITS Faculty and Students',
      'Vice Chancellor and Dean Committee Interview',
    ],
    description: 'BITS Pilani is looking for motivated faculty members passionate about teaching and research in Information Security, Cryptography, and Cyber-Physical Systems across its Indian campuses.',
    responsibilities: [
      'Teach undergraduate computer science courses including Network Security and Foundations of Data Science',
      'Build industry-partnered cyber labs with top tech firms',
      'Mentor undergraduate research projects and Practice School (PS-II) interns',
    ],
    benefits: [
      'Subsidized on-campus faculty housing with green lush surroundings',
      'Free schooling for children at Birla Public / Balika Vidya Mandir',
      'Generous relocation allowance and domestic airfare reimbursement',
    ],
    postedAt: '2026-08-18',
    applicantCount: 19,
    featured: false,
  },
  {
    id: 'job-du-cic-104',
    instituteId: 'inst-du',
    instituteName: 'University of Delhi',
    instituteShortName: 'Delhi University',
    instituteLogo: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=160&auto=format&fit=crop&q=80',
    instituteType: 'Central University (Govt. of India)',
    title: 'Assistant Professor (Level 10) in Information Technology & Mathematical Innovations',
    designation: 'Assistant Professor (Level 10 - 7th CPC)',
    department: 'Cluster Innovation Centre (CIC)',
    specializationTags: ['Data Analytics', 'Mathematical Modelling', 'Web & Mobile Systems', 'Computational Mathematics'],
    advertisementNumber: 'DU/ESTAB-IV/2026/03',
    location: {
      city: 'New Delhi',
      state: 'Delhi',
    },
    payScale: {
      cpcBand: 'Level 10 (₹57,700 - ₹1,82,400)',
      entryPay: '₹57,700',
      grossMonthlyEstimated: '₹1,12,000/mo (Entry pay + 50% DA + 27% HRA + TA)',
      allowances: ['7th CPC Dearness Allowance', 'HRA as per Delhi (X-class city)', 'Transport Allowance with DA'],
    },
    requiredQualifications: {
      minDegree: 'Master with NET/SLET',
      netSletMandatory: true,
      phdNorms: 'UGC 2009/2016 Compliant',
      minExperienceYears: 0,
      minUgcCarePubs: 2,
      ugcRegulationsYear: 'UGC 2018 Regulations',
      specializationRequirements: [
        'Master’s degree with 55% marks in Computer Applications / Computer Science / Mathematics',
        'National Eligibility Test (NET) conducted by UGC/CSIR or Ph.D. degree in compliance with UGC (Minimum Standards and Procedure for Award of M.Phil/Ph.D. Degree) Regulations, 2009/2016',
      ],
    },
    reservationCategory: 'OBC - Non Creamy Layer',
    applicationDeadline: '2026-10-05',
    status: 'published',
    isClaimedByInstitute: true,
    screeningQuestions: [
      'Confirm your UGC-NET / CSIR-NET Roll Number and Subject.',
      'Are you claiming reservation under OBC-NCL with a valid certificate issued for the current financial year?',
    ],
    selectionProcess: [
      'Scrutiny of Applications and API Score Calculation as per UGC 2018 Table 3A',
      'Shortlisting in 1:15 ratio for interview',
      'Interview before University Statutory Selection Committee',
    ],
    description: 'Cluster Innovation Centre (CIC), University of Delhi, invites applications for permanent faculty position of Assistant Professor (Level 10) under the 7th Central Pay Commission.',
    responsibilities: [
      'Teach B.Tech (Information Technology & Mathematical Innovations) students',
      'Guide hands-on student projects and industry-driven innovation challenges',
      'Engage in academic community outreach and interdisciplinary research',
    ],
    benefits: [
      'Central Government 7th CPC service conditions with NPS and LTC benefits',
      'UGC research grants for newly inducted Assistant Professors',
      'Delhi University Faculty Club and Health Centre facilities',
    ],
    postedAt: '2026-08-22',
    applicantCount: 42,
    featured: false,
  },
  {
    id: 'job-anna-it-105',
    instituteId: 'inst-anna',
    instituteName: 'Anna University',
    instituteShortName: 'Anna University',
    instituteLogo: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=160&auto=format&fit=crop&q=80',
    instituteType: 'State Public University',
    title: 'Assistant Professor (Level 10) in Computer Science & VLSI Systems',
    designation: 'Assistant Professor (Level 10 - 7th CPC)',
    department: 'Department of Information Science and Technology',
    specializationTags: ['VLSI Design', 'Embedded Systems', 'IoT Architecture', 'Hardware Security'],
    advertisementNumber: 'AU/RC/2026/IST-08',
    location: {
      city: 'Chennai',
      state: 'Tamil Nadu',
    },
    payScale: {
      cpcBand: 'Level 10 (₹57,700 - ₹1,82,400) AICTE Pay Scale',
      entryPay: '₹57,700',
      grossMonthlyEstimated: '₹1,06,000/mo (with TN Govt DA + HRA)',
      allowances: ['AICTE Career Advancement Scheme (CAS) Eligibility', 'TN Government Health Insurance Scheme'],
    },
    requiredQualifications: {
      minDegree: 'Ph.D. with First Class Master',
      netSletMandatory: true,
      phdNorms: 'UGC 2009/2016 Compliant',
      minExperienceYears: 1,
      minUgcCarePubs: 2,
      ugcRegulationsYear: 'AICTE 2019/2023 Gazette',
      specializationRequirements: [
        'B.E./B.Tech and M.E./M.Tech in ECE / CSE / VLSI Design with First Class or equivalent',
        'Ph.D. completed or submitted in relevant discipline',
        'Tamil Nadu SLET/SET or UGC/CSIR NET qualification or Ph.D. exemption',
      ],
    },
    reservationCategory: 'Scheduled Caste (SC)',
    applicationDeadline: '2026-10-10',
    status: 'published',
    isClaimedByInstitute: true,
    screeningQuestions: [
      'Do you have proficiency in Cadence / Synopsys / Xilinx EDA tool suites?',
      'Provide your valid Community Certificate details issued by Competent Authority in Tamil Nadu.',
    ],
    selectionProcess: [
      'Written Examination / AICTE Domain Subject Test',
      'Classroom Teaching Pedagogy Demonstration (15 minutes)',
      'Technical Selection Committee Interview',
    ],
    description: 'Anna University, College of Engineering Guindy campus, invites applications for the post of Assistant Professor in Information Science and Technology under State Roster reservation guidelines.',
    responsibilities: [
      'Teach undergraduate and postgraduate engineering courses',
      'Supervise laboratories and research projects in VLSI and Hardware systems',
      'Participate in NBA and NAAC accreditation documentation',
    ],
    benefits: [
      'Permanent State Government Academic Cadre position',
      'Generous research equipment support through TEQIP and State DST grants',
    ],
    postedAt: '2026-08-25',
    applicantCount: 31,
    featured: false,
  },
  {
    id: 'job-ashoka-cs-106',
    instituteId: 'inst-ashoka',
    instituteName: 'Ashoka University',
    instituteShortName: 'Ashoka University',
    instituteLogo: 'https://images.unsplash.com/photo-1576495199011-ab917353bb8f?w=160&auto=format&fit=crop&q=80',
    instituteType: 'Premier Private University',
    title: 'Assistant Professor (Tenure-Track) in Natural Language Processing & Computational Social Science',
    designation: 'Assistant Professor (Level 11 - 7th CPC)',
    department: 'Department of Computer Science',
    specializationTags: ['Natural Language Processing', 'Multilingual LLMs', 'Computational Social Science', 'Ethics in AI', 'Speech Processing'],
    advertisementNumber: 'ASHOKA/CS/FAC/2026/02',
    location: {
      city: 'Sonipat',
      state: 'Haryana',
    },
    payScale: {
      cpcBand: 'Competitive Global Scale (₹18,00,000 - ₹26,00,000 per annum)',
      entryPay: '₹1,50,000',
      grossMonthlyEstimated: '₹1,75,000/mo (Base pay + Research Allowance)',
      allowances: ['Individual Research Fund of ₹5 Lakhs/year', 'Housing Allowance', 'Annual International Conference Travel Allowance'],
    },
    requiredQualifications: {
      minDegree: 'Ph.D. Mandatory',
      netSletMandatory: false,
      phdNorms: 'Any Recognized',
      minExperienceYears: 0,
      minUgcCarePubs: 3,
      ugcRegulationsYear: 'UGC 2018 Regulations',
      specializationRequirements: [
        'Ph.D. in Computer Science, Computational Linguistics, or closely related field from an internationally reputed university',
        'High quality research agenda focused on Indic languages, NLP, or societal impacts of computing',
      ],
    },
    reservationCategory: 'Open to All Categories',
    applicationDeadline: '2026-10-31',
    status: 'published',
    isClaimedByInstitute: true,
    screeningQuestions: [
      'Provide links to your GitHub / HuggingFace model repositories if applicable.',
      'Submit your 3-page statement of teaching philosophy in a multidisciplinary liberal arts context.',
    ],
    selectionProcess: [
      'International Search Advisory Board Review',
      'Virtual Colloquium Presentation',
      'Campus Visit: Job Talk, Sample Teaching Session, and Dean Interview',
    ],
    description: 'The Department of Computer Science at Ashoka University invites tenure-track Assistant Professor applications. We offer a vibrant research environment with low teaching loads and generous research support.',
    responsibilities: [
      'Teach 2 courses per semester with low student-to-faculty ratios',
      'Lead interdisciplinary research initiatives bridging Computer Science and Social Sciences',
      'Mentor undergraduate and PhD students',
    ],
    benefits: [
      'Modern campus with faculty apartments or transport from Delhi/NCR',
      'Generous seed grants with immediate student research assistant funding',
    ],
    postedAt: '2026-08-28',
    applicantCount: 16,
    featured: true,
  },
];

export const INITIAL_CANDIDATE_PROFILE: CandidateProfile = {
  id: 'cand-prof-001',
  userId: 'user-cand-001',
  name: 'Dr. Aarav Sundaram',
  email: 'aarav.sundaram@iitb-alumni.org',
  phone: '+91-98401-23456',
  location: {
    city: 'Bengaluru',
    state: 'Karnataka',
  },
  currentDesignation: 'Postdoctoral Research Fellow',
  currentInstitute: 'IISc Bangalore (CeNSE / CDS)',
  highestDegree: 'Ph.D. in Computer Science and Engineering',
  netSletStatus: {
    isQualified: true,
    examType: 'UGC-NET (JRF)',
    qualifiedYear: 2021,
    subject: 'Computer Science and Applications',
    rollNumber: 'KA02004812',
  },
  phdStatus: {
    isCompleted: true,
    institute: 'IIT Bombay',
    thesisTitle: 'Energy-Efficient Deep Learning Accelerators and Generative Reasoning for Low-Resource Edge Devices',
    graduationYear: 2024,
    isUgc2009_2016Compliant: true,
    supervisorName: 'Prof. S. R. Ramakrishnan',
  },
  education: [
    {
      id: 'edu-1',
      degree: 'Ph.D. in Computer Science',
      field: 'Deep Learning & Edge Computing',
      institute: 'Indian Institute of Technology Bombay',
      year: 2024,
      gradePercentage: '9.4/10 CGPA',
      distinctionOrRank: 'Institute Best Dissertation Award',
    },
    {
      id: 'edu-2',
      degree: 'M.Tech in Computer Science and Engineering',
      field: 'Computer Systems and Hardware Architecture',
      institute: 'National Institute of Technology Karnataka (NITK) Surathkal',
      year: 2020,
      gradePercentage: '88.5%',
      distinctionOrRank: 'Gold Medalist (1st Rank)',
    },
    {
      id: 'edu-3',
      degree: 'B.Tech in Information Technology',
      field: 'Information Technology',
      institute: 'College of Engineering Guindy (Anna University)',
      year: 2018,
      gradePercentage: '86.2%',
      distinctionOrRank: 'First Class with Distinction',
    },
  ],
  experience: [
    {
      id: 'exp-1',
      designation: 'Postdoctoral Research Fellow',
      instituteOrCompany: 'Indian Institute of Science (IISc Bangalore)',
      department: 'Department of Computational and Data Sciences',
      startDate: '2024-07-01',
      endDate: 'Present',
      isCurrent: true,
      type: 'Research / Postdoc',
      keyAccomplishments: 'Leading research on edge-deployable multimodal language models for Indian agricultural applications; co-authored 3 IEEE Transactions papers.',
    },
    {
      id: 'exp-2',
      designation: 'Graduate Teaching Assistant',
      instituteOrCompany: 'IIT Bombay',
      department: 'Computer Science and Engineering',
      startDate: '2021-01-01',
      endDate: '2024-05-31',
      isCurrent: false,
      type: 'Teaching',
      keyAccomplishments: 'Conducted weekly lab tutorials for CS305 (Operating Systems) and CS725 (Machine Learning) with 200+ students; rated 4.8/5.0 by students.',
    },
  ],
  publications: [
    {
      id: 'pub-1',
      title: 'Scalable Quantization for Large Language Models on Heterogeneous Edge Architectures',
      journalOrConference: 'IEEE Transactions on Pattern Analysis and Machine Intelligence (TPAMI)',
      year: 2025,
      doi: '10.1109/TPAMI.2025.3289124',
      ugcCareListed: true,
      scopusIndexed: true,
      sciScieIndexed: true,
      impactFactor: 24.3,
      authors: 'A. Sundaram, S. R. Ramakrishnan, V. K. Iyer',
      citationsCount: 42,
      type: 'Journal',
    },
    {
      id: 'pub-2',
      title: 'Sub-Watt Generative Vision Transformers: Architectural Optimizations for Ultra-Low Power RISC-V Chips',
      journalOrConference: 'ACM Transactions on Embedded Computing Systems (TECS)',
      year: 2024,
      doi: '10.1145/3642189',
      ugcCareListed: true,
      scopusIndexed: true,
      sciScieIndexed: true,
      impactFactor: 4.8,
      authors: 'A. Sundaram, P. Deshmukh',
      citationsCount: 29,
      type: 'Journal',
    },
    {
      id: 'pub-3',
      title: 'Real-time Multimodal Reasoning on Distributed Micro-Clusters',
      journalOrConference: 'Proceedings of NeurIPS 2024',
      year: 2024,
      doi: '10.5555/neurips.2024.1982',
      ugcCareListed: true,
      scopusIndexed: true,
      sciScieIndexed: true,
      authors: 'A. Sundaram, K. Banerjee, S. R. Ramakrishnan',
      citationsCount: 68,
      type: 'Conference',
    },
    {
      id: 'pub-4',
      title: 'Low-Resource Indic Speech Synthesis Using Parameter-Efficient Adapter Transformers',
      journalOrConference: 'Sadhana - Academy Proceedings in Engineering Sciences (Springer / Indian Academy of Sciences)',
      year: 2023,
      doi: '10.1007/s12046-023-02104-x',
      ugcCareListed: true,
      scopusIndexed: true,
      sciScieIndexed: true,
      impactFactor: 1.6,
      authors: 'A. Sundaram, M. Krishnamurthy',
      citationsCount: 18,
      type: 'Journal',
    },
  ],
  researchInterests: [
    'Generative AI & LLMs',
    'Edge Machine Learning',
    'Hardware-Software Co-Design',
    'Indic Multimodal Systems',
    'Reinforcement Learning Systems',
  ],
  skills: [
    'PyTorch', 'TensorFlow', 'CUDA / C++', 'TVM / TensorRT', 'RISC-V Vector Extensions',
    'Distributed Training (DeepSpeed/Megatron)', 'Git', 'Linux Kernel', 'LaTeX',
  ],
  scholarLinks: {
    googleScholar: 'https://scholar.google.com/citations?user=aarav_sundaram_demo',
    orcid: '0000-0002-1823-9941',
    scopusId: '57219842100',
    researchGate: 'https://www.researchgate.net/profile/Aarav-Sundaram',
  },
  apiScore: 88,
  profileCompleteness: 95,
  resumeFileName: 'Aarav_Sundaram_Academic_CV_2026.pdf',
  resumeParsedAt: '2026-08-28T14:32:00Z',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
  bio: 'Ph.D. from IIT Bombay in Computer Science. Currently Postdoctoral Fellow at IISc Bangalore researching energy-efficient Generative AI and Edge Computing. 4 high-impact SCI/UGC-CARE publications, UGC-NET JRF qualified, and passionate about academic mentorship.',
  teachingPhilosophy: 'My teaching pedagogy blends rigorous theoretical foundations of computational systems with hands-on lab implementation. I emphasize active problem-solving, open-source contribution, and interdisciplinary research exposure for undergraduate and graduate engineers.',
};

export const INITIAL_APPLICATIONS: Application[] = [
  {
    id: 'app-001',
    jobId: 'job-iitb-cse-101',
    candidateId: 'cand-prof-001',
    jobTitle: 'Assistant Professor (Grade I - Level 12) in Artificial Intelligence & Generative Systems',
    department: 'Department of Computer Science and Engineering',
    instituteId: 'inst-iitb',
    instituteName: 'Indian Institute of Technology Bombay',
    candidateName: 'Dr. Aarav Sundaram',
    candidateEmail: 'aarav.sundaram@iitb-alumni.org',
    candidatePhone: '+91-98401-23456',
    candidateLocation: 'Bengaluru, Karnataka',
    currentDesignation: 'Postdoctoral Fellow (IISc Bangalore)',
    highestDegree: 'Ph.D. in Computer Science (IIT Bombay)',
    matchScore: 94,
    matchBreakdown: {
      overallScore: 94,
      qualificationMatch: 98,
      researchSynergy: 95,
      ugcCarePubsFit: 92,
      experienceMatch: 90,
      meetsMandatoryNetPhd: true,
      positiveSignals: [
        'Holds completed Ph.D. from IIT Bombay complying with UGC 2009/2016 norms',
        'Has 4 UGC-CARE and SCI-indexed publications in top venues (TPAMI, NeurIPS)',
        '3+ years relevant post-grad teaching and postdoctoral experience at IISc Bangalore',
        'Strong research alignment with Generative AI and Edge ML requirements',
      ],
      potentialGaps: [
        'Slightly close to minimum 3-year threshold for Grade-I Level 12; eligible for fast-track review',
      ],
    },
    status: 'shortlisted',
    stageHistory: [
      { stage: 'applied', timestamp: '2026-08-16 10:20 AM', actor: 'Candidate (Self)', note: 'Submitted application with full UGC credentials and publication dossier' },
      { stage: 'screening', timestamp: '2026-08-18 02:45 PM', actor: 'DFSC Committee Clerk', note: 'Verified PhD thesis submission certificate and UGC-NET JRF validity' },
      { stage: 'eligible', timestamp: '2026-08-20 11:30 AM', actor: 'DFSC Convener', note: 'Meets all mandatory 7th CPC Level 12 educational norms. API Score verified at 88/100.' },
      { stage: 'shortlisted', timestamp: '2026-08-24 04:15 PM', actor: 'HOD, CSE Dept', note: 'Selected for Technical Research Colloquium Presentation' },
    ],
    reviewerScores: [
      {
        reviewerId: 'rev-dean-01',
        reviewerName: 'Prof. Ramesh K. Narang',
        reviewerRole: 'Dean (Academic)',
        researchPotentialScore: 28,
        teachingPedagogyScore: 23,
        apiScoreValidation: 19,
        interviewPerformance: 23,
        totalScore: 93,
        recommendation: 'Strongly Recommend',
        confidentialNotes: 'Exceptional candidate with stellar publications (TPAMI & NeurIPS). Strong command on hardware-software co-design. Highly recommended for Level 12.',
        submittedAt: '2026-08-25 15:30',
      },
      {
        reviewerId: 'rev-hod-01',
        reviewerName: 'Prof. Sunita Krishnan',
        reviewerRole: 'Head of Department',
        researchPotentialScore: 29,
        teachingPedagogyScore: 24,
        apiScoreValidation: 20,
        interviewPerformance: 24,
        totalScore: 97,
        recommendation: 'Strongly Recommend',
        confidentialNotes: 'Candidate fills an urgent departmental teaching and research need in Generative AI systems. Teaching statement is well-articulated.',
        submittedAt: '2026-08-25 17:10',
      },
    ],
    interviewSlot: {
      date: '2026-09-12',
      time: '11:00 AM IST',
      platform: 'In-Person (Campus Selection Board Room)',
      roomVenue: 'Victor Menezes Convention Centre (VMCC), Room 204, IIT Bombay',
      committeeMembers: ['Dean of Faculty Affairs', 'HOD Computer Science', 'External Expert from TIFR', 'External Expert from IISc'],
      instructions: 'Please prepare a 35-minute presentation: 20 minutes on your Ph.D./Postdoc research contributions and 15 minutes outlining your 5-year teaching & laboratory roadmap.',
    },
    appliedDate: '2026-08-16',
    screeningAnswers: [
      { question: 'Do you have at least 2 first-author papers in Tier-1 venues (NeurIPS, ICML, CVPR, ICLR, ACL, KDD)?', answer: 'Yes, 1 paper in IEEE TPAMI (2025) and 1 paper in NeurIPS (2024).' },
      { question: 'State your total citation count and current Google Scholar h-index.', answer: '157 total citations, h-index: 4, i10-index: 4.' },
      { question: 'Briefly describe your proposed research laboratory plan and external grant potential for the next 3 years.', answer: 'I plan to establish the "Edge-AI & Efficient Systems Laboratory" targeting DST-SERB CRG and MeitY R&D funding for Indian language AI accelerators.' },
    ],
  },
  {
    id: 'app-002',
    jobId: 'job-bits-cs-103',
    candidateId: 'cand-prof-001',
    jobTitle: 'Assistant Professor (Level 10 / 11) in Cybersecurity & Cryptography',
    department: 'Department of Computer Science & Information Systems',
    instituteId: 'inst-bits',
    instituteName: 'Birla Institute of Technology and Science, Pilani',
    candidateName: 'Dr. Aarav Sundaram',
    candidateEmail: 'aarav.sundaram@iitb-alumni.org',
    candidatePhone: '+91-98401-23456',
    candidateLocation: 'Bengaluru, Karnataka',
    currentDesignation: 'Postdoctoral Fellow (IISc Bangalore)',
    highestDegree: 'Ph.D. in Computer Science (IIT Bombay)',
    matchScore: 86,
    matchBreakdown: {
      overallScore: 86,
      qualificationMatch: 95,
      researchSynergy: 80,
      ugcCarePubsFit: 90,
      experienceMatch: 85,
      meetsMandatoryNetPhd: true,
      positiveSignals: [
        'Ph.D. completed from Premier Institute of National Importance',
        'Exceeds BITS Pilani publication benchmark (4 UGC/Scopus papers vs 3 required)',
      ],
      potentialGaps: [
        'Specialization is primarily in Edge-AI / Hardware, whereas posting focuses on Cryptography & Cybersecurity',
      ],
    },
    status: 'eligible',
    stageHistory: [
      { stage: 'applied', timestamp: '2026-08-19 03:10 PM', actor: 'Candidate (Self)', note: 'Applied for Pilani and Goa campuses' },
      { stage: 'screening', timestamp: '2026-08-21 10:00 AM', actor: 'Dean Administration BITS', note: 'Documents validated' },
      { stage: 'eligible', timestamp: '2026-08-23 02:00 PM', actor: 'Faculty Selection Committee', note: 'Eligible for Departmental Shortlisting Review' },
    ],
    reviewerScores: [],
    appliedDate: '2026-08-19',
  },
  {
    id: 'app-003',
    jobId: 'job-ashoka-cs-106',
    candidateId: 'cand-prof-001',
    jobTitle: 'Assistant Professor (Tenure-Track) in Natural Language Processing & Computational Social Science',
    department: 'Department of Computer Science',
    instituteId: 'inst-ashoka',
    instituteName: 'Ashoka University',
    candidateName: 'Dr. Aarav Sundaram',
    candidateEmail: 'aarav.sundaram@iitb-alumni.org',
    candidatePhone: '+91-98401-23456',
    candidateLocation: 'Bengaluru, Karnataka',
    currentDesignation: 'Postdoctoral Fellow (IISc Bangalore)',
    highestDegree: 'Ph.D. in Computer Science (IIT Bombay)',
    matchScore: 89,
    matchBreakdown: {
      overallScore: 89,
      qualificationMatch: 95,
      researchSynergy: 88,
      ugcCarePubsFit: 88,
      experienceMatch: 82,
      meetsMandatoryNetPhd: true,
      positiveSignals: [
        'Indic speech synthesis paper published in Springer/Indian Academy of Sciences fits Ashoka multilingual focus',
        'Strong pedagogical experience at IIT Bombay',
      ],
      potentialGaps: [
        'Research is predominantly systems-focused compared to computational social science',
      ],
    },
    status: 'interview_scheduled',
    stageHistory: [
      { stage: 'applied', timestamp: '2026-08-29 09:00 AM', actor: 'Candidate (Self)', note: 'Submitted multidisciplinary teaching statement' },
      { stage: 'screening', timestamp: '2026-08-29 01:00 PM', actor: 'Ashoka Search Committee', note: 'Shortlisted for online presentation' },
      { stage: 'interview_scheduled', timestamp: '2026-08-30 04:00 PM', actor: 'Dean of Faculty Ashoka', note: 'Scheduled virtual job talk' },
    ],
    reviewerScores: [],
    interviewSlot: {
      date: '2026-09-18',
      time: '03:00 PM IST',
      platform: 'Google Meet',
      meetingLink: 'https://meet.google.com/xyz-acad-match',
      committeeMembers: ['Head of CS Department', 'Associate Dean of Sciences', 'Professor of Economics'],
      instructions: 'Virtual colloquium (40 min) followed by 20 min Q&A with Ashoka faculty and undergraduate scholars.',
    },
    appliedDate: '2026-08-29',
  },
];

export const INITIAL_DPDP_REQUESTS: DPDPDataRequest[] = [
  {
    id: 'dpdp-req-001',
    userEmail: 'dr.priya.sharma.test@gmail.com',
    userName: 'Dr. Priya Sharma',
    requestType: 'Right to Erasure (Delete all Academic CV & Personal Data)',
    status: 'Completed',
    requestedAt: '2026-08-10 11:24 AM',
    completedAt: '2026-08-12 04:00 PM',
    reason: 'Joined an international university and requested purge of Indian recruitment portal data.',
    dpoActionNotes: 'Account redacted, uploaded PDF resume purged from cloud storage, candidate profile soft-deleted and tokenized per DPDP Act Section 12.',
  },
  {
    id: 'dpdp-req-002',
    userEmail: 'dr.vikram.patel@somaiya.edu',
    userName: 'Dr. Vikram Patel',
    requestType: 'Data Portability Export (JSON/PDF)',
    status: 'Completed',
    requestedAt: '2026-08-22 09:15 AM',
    completedAt: '2026-08-22 09:16 AM',
    reason: 'Personal academic record archival.',
    dpoActionNotes: 'Automated encrypted data package containing publications, teaching record, and match scores dispatched to verified email.',
  },
  {
    id: 'dpdp-req-003',
    userEmail: 'dr.kavita.nair@cusat.ac.in',
    userName: 'Dr. Kavita Nair',
    requestType: 'Revoke AI Matching Processing Consent',
    status: 'Pending',
    requestedAt: '2026-08-30 02:40 PM',
    reason: 'Prefers manual direct application without automated profile recommendations.',
    dpoActionNotes: 'Under review by Data Protection Officer. Candidate profile will switch to private non-indexed mode.',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-001',
    timestamp: '2026-08-30 20:45:12 IST',
    actor: 'admin@acadexmatch.ai',
    actorRole: 'super_admin',
    action: 'INSTITUTE_VERIFIED',
    target: 'Ashoka University (AISHE: U-0761)',
    ipAddress: '103.21.144.92',
    complianceCategory: 'INSTITUTE_VERIFICATION',
  },
  {
    id: 'log-002',
    timestamp: '2026-08-30 19:12:04 IST',
    actor: 'facrec@iitb.ac.in',
    actorRole: 'institute_admin',
    action: 'SELECTION_COMMITTEE_SCORE_SUBMITTED',
    target: 'Application #app-001 (Dr. Aarav Sundaram)',
    ipAddress: '14.139.196.1',
    complianceCategory: 'SELECTION_COMMITTEE',
  },
  {
    id: 'log-003',
    timestamp: '2026-08-30 17:30:55 IST',
    actor: 'aarav.sundaram@iitb-alumni.org',
    actorRole: 'candidate',
    action: 'DPDP_EXPLICIT_AI_CONSENT_GRANTED',
    target: 'Candidate Profile #cand-prof-001',
    ipAddress: '49.207.214.33',
    complianceCategory: 'DPDP_CONSENT',
  },
];
